### ISSUE TITLE
Missing items on BiS Menager

### ISSUE THREAD

**Issue by Mithras2801** [zavon25/BISRedux#7]
I Dont see this item on my biss list for my mage. (and more items here)

https://www.wowhead.com/guide/classes/mage/frost/bis-gear

https://www.wowhead.com/item=193653/mask-of-imperishable-leaves?bonus=1637:7977&class=8&spec=64

**Comment by zavon25** [comment]
I'll have to look at things later today, but on a quick look, it seems the
mask you listed is from a dungeon that is not in this season's M+
rotation.  The guy that put together the items this go around appears to
only add the dungeons that will have Key drops.

So some of the Items on the Mage "BIS list" wont actually be available at
higher ilevels this season.

**Comment by Mithras2801** [comment]
Yes its not this rotation keys/dungeon, but u can add to list ? or not ?

**Comment by KayopsGaming** [comment]
Hi,
Hijacking this issue to point out that the tier items are missing from the items list.

![image](https://user-images.githubusercontent.com/73057882/207823373-6052530a-34a4-4286-b6dd-21ce75a39c7a.png)

For instance, this one is not in the list above

![image](https://user-images.githubusercontent.com/73057882/207823498-87af9f56-3412-40c0-a11a-0374eeb7367a.png)

Is this a known issue? or is there any reason for those items to not show?

Best,

**Comment by dioxina** [comment]
> Hi, Hijacking this issue to point out that the tier items are missing from the items list.
> 
> ![image](https://user-images.githubusercontent.com/73057882/207823373-6052530a-34a4-4286-b6dd-21ce75a39c7a.png)
> 
> For instance, this one is not in the list above
> 
> ![image](https://user-images.githubusercontent.com/73057882/207823498-87af9f56-3412-40c0-a11a-0374eeb7367a.png)
> 
> Is this a known issue? or is there any reason for those items to not show?
> 
> Best,

Try Version 10.0.4
